"""Mise à jour de Message

Revision ID: 64c844430d78
Revises: 2a922e72528f
Create Date: 2024-09-10 17:01:32.255050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c844430d78'
down_revision = '2a922e72528f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canal', schema=None) as batch_op:
        batch_op.drop_constraint("fk_dernier_message_id", type_='foreignkey')
        batch_op.drop_column('dernier_message_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dernier_message_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key("fk_dernier_message_id", 'message', ['dernier_message_id'], ['id'])

    # ### end Alembic commands ###
